### ISSUE TITLE
Yandex uri in "willdurand/geocoder": "~3.0" is incorrect

### ISSUE THREAD

**Issue by bubnovKelnik** [geocoder-php/BazingaGeocoderBundle#101]
Yandex has moved to https. This issue has been fixed in "willdurand/geocoder": "3.1"
But this bundle requires ~3.0. To semi-solve the problem, I should add "willdurand/geocoder": "3.2", into composer.

Suggest to change requires to "willdurand/geocoder": "3.2",

**Comment by willdurand** [comment]
done in [v4.0](https://github.com/geocoder-php/BazingaGeocoderBundle/releases/tag/4.0.0).
