### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by patkar** [geocoder-php/BazingaGeocoderBundle#102]
Since the latest stable requires `willdurand/geocoder: ~2.5` we can not profit from the the new geocoder v3. Is there any plan to release a new release from master?

If there are any tickets and and pull requests needed to finish the new release you may tag them with a intended version milestone, so everyone knows where to help?

**Comment by willdurand** [comment]
ah right. I should release v4 of this bundle then.

**Comment by patkar** [comment]
:grinning:

**Comment by willdurand** [comment]
[v4.0](https://github.com/geocoder-php/BazingaGeocoderBundle/releases/tag/4.0.0) is out!

**Comment by patkar** [comment]
You're awesome!

**Comment by willdurand** [comment]
:heart:
