### ISSUE TITLE
is there a way to replace ResultFactory or loggable_class?

### ISSUE THREAD

**Issue by Venzon** [geocoder-php/BazingaGeocoderBundle#108]
I want to add more data into geocode result but dont know if its possible to extend ResultFactory

I have implemented my own provider which returns more data but now my problem is ResultFactory which is default Geocoded

Regards

**Comment by Nyholm** [comment]
I do not think that is possible. Have a look at #127, it is similar to what 5.0 will look like. See if it is easier to solve your issue there.

**Comment by Nyholm** [comment]
This will be possible with Geocoder 4.0. GoogleMaps, BingMaps and more do this.
