### ISSUE TITLE
Major version 4.x made crash v3 cache keys retrieval

### ISSUE THREAD

**Issue by maffpool** [geocoder-php/BazingaGeocoderBundle#110]
In the last 3.x version, cached data is serialized from Geocoder 2 results (arrays)
In the actual 4.x version, data is a serialized AddressCollection

The result is : Catchable Fatal Error: Argument 4 passed to Bazinga\Bundle\GeocoderBundle\Logger\GeocoderLogger::logRequest() must be an instance of Geocoder\Model\AddressCollection, array given

Unfortunately, this is a BC sometimes difficult to handle (for example with an empty cache)

I may suggest, for new future major releases, using one of this tricks :

change the cache key name by including a version number
`$key = 'geocoder_v4_'.sha1($this->locale.$address);`

change the cache key sha1 including a version number
`$key = 'geocoder_'.sha1($this->cacheDataVersion.$this->locale.$address);`

assert cache data is formatted as expected

```
if (false !== $data = $this->cache->fetch($key)) {
    $result = unserialize($data);
    if ($result instanceof AddressCollection) {
        return $result;
    }
}
```

or maybe ensure retro compat ?

What is your opinion ?

**Comment by Nyholm** [comment]
Hm you may be right. Maybe we should include the version number in the cache key. 

I have included this in #127. (or in the cache provider)
