### ISSUE TITLE
Extend GoogleMaps provider 

### ISSUE THREAD

**Issue by Fogush** [geocoder-php/BazingaGeocoderBundle#111]
Hello,
I want to extend the GoogleMaps provider to add an ability to manipulate handling of an address parameter. In order to make this possible a new service should be created with overridden geocode method. However the method uses a private method executeQuery, also this method uses another private method updateAddressComponent. It looks like when the GoogleMapsBusiness provider was created, method buildQuery of the GoogleMaps provider was changed to protected to extend it in GoogleMapsBusiness. Can these private methods be changed to protected to extend the provider more fully?

**Comment by Nyholm** [comment]
This is fixed in version 4 of the geocoder. We use version 4 in version 5 of the bundle. See #127 for a first idea.
