### ISSUE TITLE
Version 4 broke Symfony 2.1

### ISSUE THREAD

**Issue by Arekusei** [geocoder-php/BazingaGeocoderBundle#114]
Version 4 broke Symfony 2.1
```
ErrorException: Catchable Fatal Error: Argument 1 passed to Bazinga\Bundle\GeocoderBundle\Logger\GeocoderLogger::__construct() must be an instance of Psr\Log\LoggerInterface, instance of Symfony\Bridge\Monolog\Logger given, called in \app\cache\dev\appDevDebugProjectContainer.php on line 253 and defined in \vendor\willdurand\geocoder-bundle\Bazinga\Bundle\GeocoderBundle\Logger\GeocoderLogger.php line 34
```
Version 2.1 LoggerInterface used from Symfony framework not PSR,

**Comment by Nyholm** [comment]
`Symfony\Bridge\Monolog\Logger` is a `Psr\Log\LoggerInterface`. Not sure if it was in sf2.1 though. 

Im closing this issue since it is super old and SF2.1 is not supported anymore.

**Comment by Arekusei** [comment]
@Nyholm In `composer.json`
```
"symfony/framework-bundle": "~2.1|~3.0",
```

**Comment by Nyholm** [comment]
I was referring to master: https://github.com/geocoder-php/BazingaGeocoderBundle/blob/master/composer.json#L16

**Comment by Arekusei** [comment]
When I had problems It was not fixed. And as I see release has not happened yet. https://github.com/geocoder-php/BazingaGeocoderBundle/blob/4.2.0/composer.json#L14

The problem is that if you install a bundle on symfony 2.1 or any other without PSR Logger support, the composer tries to install version 4.x which is actually incompatible because it requires PSR Logger. As I understand this problem can not be solved simply by updating since it is necessary to completely replace old versions which have incompatible dependencies.
Anyway, now it is already for me not an actual problem.

But thanks for you answers.
