### ISSUE TITLE
Documentation: How to use Chain Provider?

### ISSUE THREAD

**Issue by BallisticPain** [geocoder-php/BazingaGeocoderBundle#163]
I think a useful example in many circumstances will be a chain provider. I am going to try to figure it out myself, but thought it would be a useful bit in the docs. If I do figure it out I'll reference this ticket in my PR.

Also, the `services` config key isn't mentioned in the configuration section of the documentation. From reading through the code, I believe this would be under a `providers:` sub key?

Thanks!
Jarvis

**Comment by Nyholm** [comment]
I agree that it should be documeneted. I would be happy to review a PR. 
Have a look at this issue for the answer https://github.com/geocoder-php/BazingaGeocoderBundle/issues/161

**Comment by Nyholm** [comment]
Closed by #164
