### ISSUE TITLE
integer cast on cache_lifetime return 0 instead of null if not provided

### ISSUE THREAD

**Issue by lwillems** [geocoder-php/BazingaGeocoderBundle#215]
in BazingaGeocoderExtension

`
$container->register($providerServiceId.'.cache', CachePlugin::class)
                ->setPublic(false)
                ->setArguments([new Reference($cacheServiceId), (int) $config['cache_lifetime'], $config['cache_precision']]);
`

casting argument as (int) make it default to 0 in cachePlugin __construct instead of null if provided in yaml conf : 
`cache_lifetime: ~`

Consequence :  infinite caching is not possible

Regards

**Comment by norkunas** [comment]
Hello @lwillems, would you like to submit a PR to fix this?

**Comment by norkunas** [comment]
@lwillems this was fixed in #249
