### ISSUE TITLE
Factory deprecation notices cannot be ignored

### ISSUE THREAD

**Issue by sarcher** [geocoder-php/BazingaGeocoderBundle#259]
With the deprecation notices introduced in the class definitions of `GeoIPsFactory` and `MapzenFactory` there doesn't seem to be a way to not see them on container build. The `Resources/config/services.yml` file includes:

```
    Bazinga\GeocoderBundle\ProviderFactory\:
        resource: '../../ProviderFactory'
        public: false
        autoconfigure: true
```

This causes the deprecation to trigger, with no way to avoid it other than excluding the class from the classmap in Composer, but that in turn causes a different error.

One possible solution would be to add an `exclude` right under that to exclude them, but would break it for anybody else using them still.

Am I missing something, or are there any other ideas on how to avoid these notices? Thanks!

**Comment by norkunas** [comment]
@sarcher I don't think there is a easy way to hide them, but as long as you are not using them you don't need to change something, those factories will be removed since next major and the deprecations will be gone.

**Comment by sarcher** [comment]
That's unfortunate; we actually treat deprecation as failure in our forward-looking CI, so it's very annoying to have these. I suppose we can downgrade the bundle or fork it and remove those, but it would be nice to have an option to not auto-load the providers that aren't being used.

Maybe that could be a configuration option, where if it is set, only the providers explicitly configured are loaded?

**Comment by norkunas** [comment]
@Nyholm what's your opinion about this?

**Comment by Nyholm** [comment]
Oh, This is super interesting. 
I did not predict this behavior. =)

But what if we trigger an deprecation error only when we are using the factory? Ie we move [this line](https://github.com/geocoder-php/BazingaGeocoderBundle/blob/5.9.0/ProviderFactory/GeoIPsFactory.php#L20) down to the `getProvider()` function?

Wouldn't that work?

**Comment by sarcher** [comment]
I think that would work for us. The danger of putting `@trigger_error` outside of the class itself is that it will show up even from things like Composer class loader operations.

**Comment by norkunas** [comment]
@sarcher wanna make a PR?

**Comment by sarcher** [comment]
@norkunas should be all set; I tested with/without the change and it seems to work as advertised. If there's any chance of tagging a new minor version with this change that would be wonderful. Thanks!

**Comment by norkunas** [comment]
@sarcher I've tagged this as a fix release.
