### ISSUE TITLE
Symfony 5 support

### ISSUE THREAD

**Issue by OwlyCode** [geocoder-php/BazingaGeocoderBundle#269]
Hello,

Do you plan to add Symfony 5 support? I forked this bundle and made it ready for Symfony 5 but there is a BC break that will make Symfony 3.4 no longer supported on PHP less than 7.4 : the `DataCollectorInterface::collect` signature changed and contravariant parameter support has only been added in PHP 7.4.

I can provide you the PR but what can we do about Symfony 3.4?

**Comment by norkunas** [comment]
Hello, see #266. The data collector will be supported from 3.4+
