### ISSUE TITLE
Another Factory

### ISSUE THREAD

**Issue by methodeprog** [geocoder-php/BazingaGeocoderBundle#272]
Dear Sir
Just a suggestion, is there a way to create MapBoxFactory like Bazinga\GeocoderBundle\ProviderFactory\GoogleMapsFactory.
I'm  MapBox user so i'm looking for a clean way to do it with your bundle.
Thanks

**Comment by norkunas** [comment]
@methodeprog have you solved this? If not, what did you try? By changing the provider to the MapBoxFactory it should be enough, just make sure to provide required options.
