### ISSUE TITLE
Class GeocoderDataCollector must implement method reset

### ISSUE THREAD

**Issue by uginroot** [geocoder-php/BazingaGeocoderBundle#279]
Php say:

> Class Bazinga\GeocoderBundle\DataCollector\GeocoderDataCollector contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Contracts\Service\ResetInterface::reset)

**Comment by norkunas** [comment]
@uginroot which symfony/this lib version you use? Because if you'd look at the source GeocoderDataCollector contains the reset method.

**Comment by uginroot** [comment]
>php bin/console about
 -------------------- ------------------------------------------------------------------------
  Symfony
 -------------------- ------------------------------------------------------------------------
  Version              4.4.5

**Comment by uginroot** [comment]
Command `composer require willdurand/geocoder-bundle:^5.11` solved my problem

**Comment by norkunas** [comment]
I'm glad that you find the solution :+1: :slightly_smiling_face:
