### ISSUE TITLE
Does this work for Symfony 4? 

### ISSUE THREAD

**Issue by vincentcox** [geocoder-php/BazingaGeocoderBundle#291]
The documentation is talking of `app/config/config.yml` which is not used in Symfony 4 if you use autowiring.
I am trying to use the NominatimGeocoder, but it seems not to work. 
```
    private $NominatimGeocoder;

    public function __construct(Provider $NominatimGeocoder)
    {
        $this->NominatimGeocoder = $NominatimGeocoder;
    }
```

`Cannot autowire service "App\Controller\myController": argument "$NominatimGeocoder" of method "__construct()" references interface "Geocoder\Provider\Provider" but no such service exists. You should maybe alias this interface to the existing "Geocoder\ProviderAggregator" service.`

**Comment by norkunas** [comment]
Yes it should work :) Did you try to write as `$nominatimGeocoder`?

**Comment by vincentcox** [comment]
@nicolas-grekas The clue is: where do you have to configure this in Symfony 4? I, the services.yaml file?

Good cue for the different `nominatimGeocoder` naming, if you let me know where to configure this, I'll try again! Thanks!

**Comment by nicolas-grekas** [comment]
in services.yaml I suppose yes
but this should be handled by the bundle also, which need to ship with autowiring aliases.
I suppose this could be submitted as a PR.

**Comment by norkunas** [comment]
This bundle ships those autowiring aliases already :)

**Comment by norkunas** [comment]
So did it work for you?

**Comment by vincentcox** [comment]
Really kind to check in. I will check later this evening and will close this issue if solved!

**Comment by rkonopski** [comment]
It works even on Symfony 5.2 :)
