### ISSUE TITLE
Support for PHP8

### ISSUE THREAD

**Issue by StephaneLeveugle** [geocoder-php/BazingaGeocoderBundle#295]
Hi,

I'm using this package and I'd like to upgrade to PHP8, geocoder already supports PHP8 if i'm not mistaken.

I'm aware this PR exists: https://github.com/geocoder-php/BazingaGeocoderBundle/pull/294 but it doesn't look like it will get finished/merged.

Could someone take care of this?

Thank you

**Comment by norkunas** [comment]
Maybe you could try to finish this :)

**Comment by norkunas** [comment]
Done in #299
