### ISSUE TITLE
Update Doc to Symfony 4.3+

### ISSUE THREAD

**Issue by Mausino** [geocoder-php/BazingaGeocoderBundle#305]
Autowiring + Flex change (made revolution) in symfony environment.

Will nice if will documentation only for Symfony 4.3+ if you're in this bundle in v5.14 deprecate Symfony 3.4

For me as newbie is very confusing documentation.. because i never used before Symfony 3+ and still searching if this exist in Symfony 5.2+ in my case

Things like acme, register in appkernel and so on.. confused me when i began with this great bundle

**Comment by Chris53897** [comment]
Can you describe what is outdated? Beside of your PR https://github.com/geocoder-php/BazingaGeocoderBundle/pull/304

This [section](https://github.com/geocoder-php/BazingaGeocoderBundle/blob/master/Resources/doc/index.md#doctrine-test) could be updated as well for composer and phpunit 9. But that is just a small change that is not so important.

**Comment by Chris53897** [comment]
@Mausino Can this issue be closed? The docs are updated, can you please verify if it is better understandable now?
