### ISSUE TITLE
Issue installing v. 5.16.1

### ISSUE THREAD

**Issue by henrikac** [geocoder-php/BazingaGeocoderBundle#321]
When I try to install `composer require willdurand/geocoder-bundle:5.16.1` I get the following error:

```
  Problem 1
    - geocoder-php/plugin 1.3.0 requires psr/log ^1.0 -> found psr/log[1.0.0, ..., 1.1.4] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - willdurand/geocoder-bundle 5.16.1 requires geocoder-php/plugin ^1.3 -> satisfiable by geocoder-php/plugin[1.3.0].
    - Root composer.json requires willdurand/geocoder-bundle 5.16.1 -> satisfiable by willdurand/geocoder-bundle[5.16.1].
```

I have checked the `composer.json` file in `geocoder-php/plugin` and it looks fine to me.

## Possible solution

I think a possible solution could be to:
1. add a new release to `geocoder-php/plugin` (e.g. `v1.3.1`)
2. add this version to `geocoder-php/BazingaGeocoderBundle/composer.json`
3. upgrade `geocoder-php/BazingaGeocoderBundle` to version `5.16.2`

```
PHP: 8.0.14
Composer: 2.1.12
Symfony: 6.0.*
```

**Comment by norkunas** [comment]
This bundle does not have a direct dependency on psr/log and is also maintained separately :) See https://github.com/geocoder-php/Geocoder/issues/1145

**Comment by henrikac** [comment]
But this bundle depends on `geocoder-php/plugin ^1.3` which depends on `psr/log ^1.0` instead of `psr/log "^1.0|^2.0|^3.0"` because no new minor release was made when the `composer.json` was updated (I think).

But the issue you linked to mentions that new releases will be created before the end of this year (this week). I guess I'll just wait for those releases and hope it will fix the issue :)

**Comment by henrikac** [comment]
The new releases mentioned in geocoder-php/Geocoder#1145 fixes my issue when I try to install this bundle in Symfony 6! 🥳🥳
