### ISSUE TITLE
Unknown function "dump"

### ISSUE THREAD

**Issue by AlexHaaniWink** [geocoder-php/BazingaGeocoderBundle#355]
In geocoder.html.twig the method `dump` is used once: https://github.com/geocoder-php/BazingaGeocoderBundle/blob/master/templates/Collector/geocoder.html.twig#L102

Further along `profiler_dump` is used. Shouldn't that first also be like this?

Somehow this triggers an error on our production servers. Though I'm not yet sure how. And I doubt that `profiler_dump` is available then anyway.
`Unknown function "dump"`

I've found this similar issue in a different project: https://github.com/api-platform/core/issues/5786

**Comment by norkunas** [comment]
Will check this tomorrow, but why your production servers/projects are accessing/using dev template in the first place?

**Comment by AlexHaan-i** [comment]
Thanks!

You asked for a stack trace.

We use `kriswallsmith/assetic` in our Symfony projects (old Symfony version - working on it...).
Somehow Assetic dump finds this template as a resource and loads it. Even in production.

I haven't yet figured out completely why that happens. But since you asked for a stack trace:

```
bin/console in run at line 44
vendor/symfony/symfony/src/Symfony/Component/Console/Application.php in doRun at line 148
vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php in doRun at line 74
vendor/symfony/symfony/src/Symfony/Component/Console/Application.php in doRunCommand at line 255
vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php in doRunCommand at line 86
vendor/symfony/symfony/src/Symfony/Component/Console/Application.php in run at line 1010
vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php in execute at line 255
(project own wrapper around the Assetic DumpCommand) .../Assetic/Command/DumpCommand.php ...
vendor/symfony/assetic-bundle/Command/DumpCommand.php in getNames at line 117
vendor/kriswallsmith/assetic/src/Assetic/Factory/LazyAssetManager.php in load at line 195
vendor/kriswallsmith/assetic/src/Assetic/Factory/LazyAssetManager.php in load at line 160
vendor/kriswallsmith/assetic/src/Assetic/Factory/Loader/CachedFormulaLoader.php in load at line 59
```

**Comment by norkunas** [comment]
Thanks. Okay so I've replaced it with `profiler_dump` already, can you test it if it fixes your issue?

**Comment by AlexHaan-i** [comment]
I'll have to update and see at a later time (with some days off coming up).
I doubt that would help in our case though. Since `profiler_dump` shouldn't be defined either, right?

We just need to prevent it from being loaded when it shouldn't.

**Comment by norkunas** [comment]
Probably yes :man_shrugging:
