### ISSUE TITLE
[RFC] Refactoring Result factories

### ISSUE THREAD

**Issue by toin0u** [geocoder-php/BazingaGeocoderBundle#61]
Hi,

The bundle is now compatible with Geocoder 2.3 and upper. It means that we should refactor the result factories to the bundle. In this way, we need to adapt the command, the logger and providers as we can get mutilple results now.

For the providers, it's not a problem but how do you think we should implement the command and the logger ?

**Comment by Nyholm** [comment]
Closing this very old issue. I do not think it is relevant anymore. Feel free to open it again if you disagree.
