### ISSUE TITLE
Need proxy configuration for adapters

### ISSUE THREAD

**Issue by wasinger** [geocoder-php/BazingaGeocoderBundle#75]
Our server is behind a firefall and access to the internet is only available via proxy. Is there a way to specify proxy settings for the Geocoder HTTPAdapters?

**Comment by bubnovKelnik** [comment]
You can setup service (set proxy,timeout, etc..) and set is as argument to 
bazinga_geocoder:
    adapter

See https://github.com/geocoder-php/BazingaGeocoderBundle/blob/master/Resources/doc/index.md#custom-http-adapter

**Comment by Nyholm** [comment]
With #127 you will have control over the HttpClient by HTTPlug. You can control the proxy there. 

It will be available in version 5. Im closing this issue now. Feel free to open a new issue if you still have questions
