### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by cassianotartari** [geocoder-php/BazingaGeocoderBundle#84]
Hello!

Is there anybody that had encoding problems with this bundle?

For example:
```php
object(Geocoder\Result\Geocoded)[623]
  protected 'latitude' => float -27.5833
  protected 'longitude' => float -48.5667
  protected 'bounds' => null
  protected 'streetNumber' => null
  protected 'streetName' => null
  protected 'cityDistrict' => null
  protected 'city' => string 'Florian?polis' (length=13)
  protected 'zipcode' => null
  protected 'county' => null
  protected 'countyCode' => null
  protected 'region' => null
  protected 'regionCode' => string '26' (length=2)
  protected 'country' => string 'Brazil' (length=6)
  protected 'countryCode' => string 'BR' (length=2)
  protected 'timezone' => null
```
City with an accent is being returning with a ``?``

My page has ``<meta charset="utf-8" />`` setted.

Thanks.

**Comment by cassianotartari** [comment]
Sorry for late answser @toin0u I was traveling, you can test with my actual ip: ``189.26.128.80`` that points to ``Florianópolis``

**Comment by cassianotartari** [comment]
Thanks @toin0u !
What should I do to merge this update to my code? I using ``"willdurand/geocoder": "@stable",``. Just using your fork or waiting the merge into ``stable``?

**Comment by toin0u** [comment]
@cassianotartari You're welcome :) @willdurand will review it, merge it and release a version of the `Geocoder 2.8.2` and then a `composer update willdurand/geocoder-bundle` should work :) I don't think William will bump a new version for the bundle.

**Comment by cassianotartari** [comment]
:+1: I'll be waiting the merge to close this issue. Thanks again.

**Comment by toin0u** [comment]
Nice! Thanks! :D

**Comment by cassianotartari** [comment]
Great job guys! It's working!

**Comment by toin0u** [comment]
:+1:
