### ISSUE TITLE
Upgrade to Geocoder v3

### ISSUE THREAD

**Issue by willdurand** [geocoder-php/BazingaGeocoderBundle#91]

**Comment by AntoineLemaire** [comment]
Any idea when you have finished upgrading ? :)

**Comment by nicolassing** [comment]
Do you need some help ? Let me know if i can help :)

**Comment by FredoVelcro** [comment]
I really need geocoder ~3.1, how to do then ?
Thank you

**Comment by FredoVelcro** [comment]
ping @willdurand

**Comment by willdurand** [comment]
Feel free to work on it! I can't provide a PR right now unfortunately, and other maintainers are quite busy too.

**Comment by FredoVelcro** [comment]
With pleasure ! ;)

**Comment by willdurand** [comment]
Done by PR #96

**Comment by willdurand** [comment]
A stable release should be available next Monday
