### ISSUE TITLE
GoogleMaps "Could not execute query" instead of "SSL certificate problem: "unable to get local issuer certificate"

### ISSUE THREAD

**Issue by IMM0rtalis** [geocoder-php/BazingaGeocoderBundle#92]
Heyho...

i am wondering for a time now why i am getting "Could not execute query" exception with googleMaps, but if I type the query manuel there are correct results.

After a while of debugging i found the solution(the problem) in the curl-request:
"SSL certificate problem: "unable to get local issuer certificate"

Wouldn't it be nice or a better errordescription if this would be the text instead of simply just "Could not execute query"?

Maybe this issue-ticket will help others ;)

Best regards,
Florian Scholz

**Comment by Baachi** [comment]
First of all this should be a reported to the main repo [https://github.com/geocoder-php/Geocoder]. 

And if you have a better solution, just make a PR. We are happy about each contribution.
